
DROP SEQUENCE APP_ATTACH_SEQ;
DROP SEQUENCE DOC_TEMP_SEQ;
DROP SEQUENCE APP_LINE_SEQ;
DROP SEQUENCE APP_DOC_SEQ;

CREATE SEQUENCE APP_DOC_SEQ NOCACHE;
CREATE SEQUENCE APP_LINE_SEQ NOCACHE;
CREATE SEQUENCE DOC_TEMP_SEQ NOCACHE;
CREATE SEQUENCE APP_ATTACH_SEQ NOCACHE;

DROP TABLE DOC_T;
DROP TABLE REFERENCE_T;
DROP TABLE APP_ATTACH_T;
DROP TABLE DOC_TEMP_T;
DROP TABLE APP_LINE_T;
DROP TABLE APPROVAL_T;
DROP TABLE APP_DOC_T;

-- 전자결재 문서 테이블
CREATE TABLE APP_DOC_T (
    DOC_ID        NUMBER NOT NULL,                         -- 문서번호
    EMP_ID       NUMBER NOT NULL,                         -- 사원ID
    TITLE         VARCHAR2(200 BYTE),                      -- 문서제목
    CONTENTS     VARCHAR2(3000 BYTE),                     -- 문서내용
    DOC_TEMP_CODE NUMBER,                                  -- 문서양식코드
    WRITE_DT      DATE,                                    -- 기안일자
    UPDATE_DT     DATE,                                    -- 수정일자
    DEP_ID        NUMBER,                                  -- 부서ID
    DOC_STATE     VARCHAR2(2 BYTE) DEFAULT '0' NOT NULL, -- 문서상태
    URGENT        VARCHAR2(2 BYTE) DEFAULT '0' NOT NULL,  -- 긴급여부
    CONSTRAINT PK_APP_DOC PRIMARY KEY (DOC_ID)
);

-- 결재 테이블
CREATE TABLE APPROVAL_T (
    APP_ID      NUMBER                        NOT NULL, -- 결재번호
    DOC_ID      NUMBER                        NOT NULL, -- 문서번호
    APP_STATE   VARCHAR2(2 BYTE) DEFAULT '0' NOT NULL, -- 결재상태
    EMP_ID     NUMBER                        NOT NULL,  -- 사원ID
    SUBMIT_DT   DATE,                                    -- 상신일자
    APP_DT      DATE,                                    -- 결재승인일자
    APP_DOC_ID  VARCHAR2(100 BYTE),                      -- 결재문서번호
    REJECT     VARCHAR2(100 BYTE),                      -- 반려사유
    LINE_ORDER  VARCHAR2(100 BYTE),                     -- 결재순서
    CONSTRAINT PK_APPROVAL PRIMARY KEY (APP_ID)
);

-- 결재라인 테이블 (결재선 즐겨찾기 테이블)
CREATE TABLE APP_LINE_T (
    LINE_ID        NUMBER              NOT NULL, -- 내 결재라인번호
    LINE_TYPE      VARCHAR2(100 BYTE),           -- 결재선 종류(이름)
    EMP_ID         NUMBER              NOT NULL, -- 사원ID
    LINE_FAV_ORDER VARCHAR2(100 BYTE) NOT NULL, -- 결재선 순서
    REGISTER      VARCHAR2(100 BYTE),           -- 등록자
    REGISTER_DT    DATE,                          -- 등록일
    UPDATER        VARCHAR2(100 BYTE),           -- 수정자
    UPDATE_DT      DATE,                          -- 수정일
    CONSTRAINT PK_APP_LINE PRIMARY KEY(LINE_ID)
);

-- 문서양식 테이블
CREATE TABLE DOC_TEMP_T (
    DOC_TEMP_CODE NUMBER NOT NULL,         -- 문서양식코드
    DOC_TEMP_NAME VARCHAR2(100 BYTE),      -- 문서양식명
    CONTENTS     VARCHAR2(3000 BYTE),     -- 문서양식내용
    CONSTRAINT   PK_DOC_TEMP PRIMARY KEY(DOC_TEMP_CODE)
);

-- 첨부파일 테이블
CREATE TABLE APP_ATTACH_T (
    ATTACH_NO        NUMBER NOT NULL,    -- 파일번호
    ATTACH_ID        VARCHAR2(100 BYTE), -- 파일명
    ORIGINALFILENAME VARCHAR2(100 BYTE), -- 파일원본이름
    UPLOAD_PATH      VARCHAR2(200 BYTE), -- 파일경로
    DOC_ID           NUMBER,              -- 문서번호
    CONSTRAINT PK_APP_ATTACH PRIMARY KEY(ATTACH_NO)
);

-- 참조자 테이블
CREATE TABLE REFERENCE_T (
    DOC_ID  NUMBER NOT NULL, -- 문서번호
    REF_TYPE CHAR(2 BYTE),   -- 참조 구분
    EMP_ID NUMBER,           -- 참조 사원ID
    DEPT_ID NUMBER,          -- 참조 부서ID
    CONSTRAINT PK_REFERENCE PRIMARY KEY(DOC_ID)
);

CREATE TABLE DOC_T (
DOC_ID NUMBER NOT NULL,
ITEM_NAME VARCHAR2(100 BYTE),
ITEM_STANDARD VARCHAR2(100 BYTE),
ITEM_QUAN VARCHAR2(100 BYTE),
ITEM_COST NUMBER,
AMOUNT NUMBER,
REMARKS VARCHAR2(100 BYTE),
CONSTRAINT PK_DOC PRIMARY KEY(DOC_ID)
);

/*

ALTER TABLE REFERENCE_T ADD CONSTRAINT FK_REFERNCE_APP_DOC FOREIGN KEY(DOC_ID) REFERENCES APP_DOC_T(DOC_ID) ON DELETE CASCADE;

ALTER TABLE REFERENCE_T ADD CONSTRAINT FK_REFERNCE_USER FOREIGN KEY(USER_ID) REFERENCES USER_T(USER_ID) ON DELETE CASCADE;

ALTER TABLE REFERENCE_T ADD CONSTRAINT FK_REFERNCE_DEP FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT_T(DEP_ID) ON DELETE CASCADE;

-- 전자결재 문서 테이블 
ALTER TABLE APP_DOC_T ADD CONSTRAINT FK_APP_DOC_USER FOREIGN KEY(USER_ID) REFERENCES USER_T(USER_ID) ON DELETE SET NULL;

ALTER TABLE APP_DOC_T ADD CONSTRAINT FK_APP_DOC_DOC_TEMP FOREIGN KEY(DOC_TEMP_CODE) REFERENCES DOC_TEMP_T(DOC_TEMP_CODE) ON DELETE SET NULL;    

ALTER TABLE APP_DOC_T ADD CONSTRAINT FK_APP_DOC_DEP FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT_T(DEP_ID) ON DELETE SET NULL;


-- 결재 테이블
ALTER TABLE APPROVAL_T ADD CONSTRAINT FK_APPROVAL_APP_DOC FOREIGN KEY(DOC_ID) REFERENCES APP_DOC_T(DOC_ID) ON DELETE CASCADE;

ALTER TABLE APPROVAL_T ADD CONSTRAINT FK_APPROVAL_DEP FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT_T(DEP_ID) ON DELETE SET NULL;


-- 결재라인 테이블 (결재선 즐겨찾기 테이블)
ALTER TABLE APP_LINE_T ADD CONSTRAINT FK_APP_LINE_USER FOREIGN KEY(USER_ID) REFERENCES USER_T(USER_ID) ON DELETE CASCADE;


-- 첨부파일 테이블
ALTER TABLE APP_ATTACH_T ADD CONSTRAINT FK_APP_ATTACH_APP_DOC FOREIGN KEY(DOC_ID) REFERENCES APP_DOC_T(DOC_ID) ON DELETE CASCADE;


-- 참조자 테이블
ALTER TABLE REFERENCE_T ADD CONSTRAINT FK_REFERNCE_APP_DOC FOREIGN KEY(DOC_ID) REFERENCES APP_DOC_T(DOC_ID) ON DELETE CASCADE;

ALTER TABLE REFERENCE_T ADD CONSTRAINT FK_REFERNCE_USER FOREIGN KEY(USER_ID) REFERENCES USER_T(USER_ID) ON DELETE CASCADE;

ALTER TABLE REFERENCE_T ADD CONSTRAINT FK_REFERNCE_DEP FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT_T(DEP_ID) ON DELETE CASCADE;

*/

